### ISSUE TITLE
Rust Struct -> Elixir Map

### ISSUE THREAD

**Issue by praveenperera** [sunny-g/serde_rustler#10]
When I try to deserialize a rust struct I get InvalidStructKey, this struct comes from a different library so I can't rename it.

Is it possible to just deserialize it into an elixir map instead of an elixir struct?

**Comment by praveenperera** [comment]
I ended up using serde_json and serde_transcode to do it:

https://github.com/avencera/fast_rss/blob/0bda339952b379e675bf4c92c5b84bcc220f1e7e/native/fastrss/src/lib.rs#L32

**Comment by sunny-g** [comment]
Alternatively, I think you can use the serde [`remote`](https://serde.rs/remote-derive.html) attribute to customize ser/de behaviour for foreign types.

**Comment by praveenperera** [comment]
I should try that, thanks!

Do you think that might be faster than how I'm currently doing it?

**Comment by sunny-g** [comment]
I believe so, as it'll 1) do the translation in Rust vs Elixir, and 2) I believe that no conversion is actually involved in the `derive` macro and `remote` attribute.
