### ISSUE TITLE
Including as dependency produces build error

### ISSUE THREAD

**Issue by sachanganesh** [sunny-g/serde_rustler#5]
Thanks for the interesting project! I'm experimenting with NIFs and Rustler in Elixir and I came across your library.

Unfortunately, if I simply add the `serde_rustler` crate to the dependency list and attempt to build my project, I get the following error:

```
Compiling NIF crate :patricia_tree_nif (native/patricia_tree_nif)...
    Updating crates.io index
   Compiling erlang_nif-sys v0.6.4
   Compiling rustler v0.20.0
error: failed to run custom build command for `erlang_nif-sys v0.6.4`

Caused by:
  process didn't exit successfully: `/home/svganesh/Documents/projects/lilac/_build/test/rustler_crates/patricia_tree_nif/release/build/erlang_nif-sys-4d7d59c73cc1a8e4/build-script-build` (exit code: 101)
--- stdout
Unsupported Erlang version.

Is the erlang_nif-sys version up to date in the Cargo.toml?
Does 'cargo update' fix it?
If not please report at https://github.com/goertzenator/erlang_nif-sys.

--- stderr
thread 'main' panicked at 'gen_api.erl encountered an error.', /home/svganesh/.cargo/registry/src/github.com-1ecc6299db9ec823/erlang_nif-sys-0.6.4/build.rs:28:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `rustler v0.20.0`

Caused by:
  process didn't exit successfully: `/home/svganesh/Documents/projects/lilac/_build/test/rustler_crates/patricia_tree_nif/release/build/rustler-41fcd3f19ec469c1/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Erlang version 2.15 not handled, please file a a bug report.', src/libcore/option.rs:1034:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

** (RuntimeError) Rust NIF compile error (rustc exit code 101)
    lib/mix/tasks/compile.rustler.ex:68: Mix.Tasks.Compile.Rustler.compile_crate/1
    (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
    lib/mix/tasks/compile.rustler.ex:15: Mix.Tasks.Compile.Rustler.run/1
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
    (mix) lib/mix/tasks/compile.all.ex:73: Mix.Tasks.Compile.All.run_compiler/2
    (mix) lib/mix/tasks/compile.all.ex:53: Mix.Tasks.Compile.All.do_compile/4
    (mix) lib/mix/tasks/compile.all.ex:24: anonymous fn/1 in Mix.Tasks.Compile.All.run/1
    (mix) lib/mix/tasks/compile.all.ex:40: Mix.Tasks.Compile.All.with_logger_app/1

```

As the error output suggested, I did `cd` into the NIF directory and attempt `cargo update`, but it didn't help. I assume it's an issue with my settings/versions and this library, as removing `serde_rustler` from the dependency list in Cargo.toml removes the build errors.

The following is the contents of my Cargo.toml:

```
[package]
name = "patricia_tree_nif"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "patricia_tree_nif"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.21.0"
lazy_static = "1.0"
uuid = "0.8.1"
bitvec = "0.15.2"
serde_rustler = "0.0.3"
```

My environment settings are:

- Ubuntu 16.04.6 LTS
- rustc 1.37.0
- cargo 1.37.0
- Erlang/OTP 22 [erts-10.5.1]
- Elixir 1.9.1 (compiled with Erlang/OTP 21)

---

Thanks again for your work!

**Comment by sachanganesh** [comment]
I think this issue might be resolved when the `erlang_nif-sys` project is able to support Erlang 22. See https://github.com/rusterlium/erlang_nif-sys/pull/39. Perhaps it also might be resolved if this project is updated to Rustler v0.21.0, though I'm not sure.

Please let me know your thoughts!

**Comment by SkipMike** [comment]
I think it related to the OTP version, but I had to downgrade to OTP 21 to resolve my issue when I hit this.

**Comment by evnu** [comment]
Note that you can work around version problems as described [here](https://github.com/rusterlium/rustler#supported-nif_version) until they are fixed upstream:

```
RUSTLER_NIF_VERSION=2.14 mix compile
```

But rustler 0.21 supports OTP 22, so this should not be an issue anymore since [this](https://github.com/sunny-g/serde_rustler/commit/cf4bcbd8928847d205ee481ef86b2ebf4bc7cb87) commit to serde_rustler.

**Comment by sachanganesh** [comment]
Haven't tried it out myself, but I'll take your word for it! Thanks a bunch 👍
