### ISSUE TITLE
Release new version?

### ISSUE THREAD

**Issue by praveenperera** [sunny-g/serde_rustler#9]
Can you release a new version with the commits that support OTP 22?

**Comment by sunny-g** [comment]
I'm not using Elixir anymore, so if you could create a PR for it, I'd be happy to accommodate.

**Comment by praveenperera** [comment]
It works after this commit: https://github.com/sunny-g/serde_rustler/commit/cf4bcbd8928847d205ee481ef86b2ebf4bc7cb87

I was just wondering if you could publish the new to crates.io 

I'll make a PR with bumped version and changelog
